### ISSUE TITLE
Serialize Clarity values

### ISSUE THREAD

**Issue by sergey-shandar** [Trust-Machines/core-eng#113]
See `stacks.js`
See https://github.com/fungible-systems/micro-stacks

**Comment by igorsyl** [comment]
@sergey-shandar please follow project management guidelines here: https://github.com/Trust-Machines/core-eng/pull/122

**Comment by kantai** [comment]
I commented in the zoom chat last week, but if you're looking to serialize Clarity values and parameters from rust, the `stacks-common` and `libclarity` library outputs from the stacks-blockchain repo can provide you with what you need.

`libclarity::vm::type::Value` structs implement `StacksMessageCodec`, but a bunch of other serialization methods too. Those serializations can be deserialized from within a Clarity contract using `from-consensus-buff?` or generated using `to-consensus-buff?`

The Hiro subnets repo has a couple examples of doing this with signatures over data. This contract checks a signature and validates the underlying content by generating the input buffer using `to-consensus-buff?` 

https://github.com/hirosystems/stacks-subnets/blob/master/core-contracts/contracts/multi-miner.clar#L58-L65

That hash is also generated in rust code in the block proposal signer method:

https://github.com/hirosystems/stacks-subnets/blob/master/src/chainstate/stacks/miner.rs#L2331-L2378

**Comment by sergey-shandar** [comment]
PR #130
