### ISSUE TITLE
[stacks-coordinator] translate js-rpc StacksTransaction to blockstack_lib StacksTransaction

### ISSUE THREAD

**Issue by donpdonp** [Trust-Machines/core-eng#172]
from @stjepangolemac in #88 
> Okay so I've used the `StacksTransaction` introduced by @sergey-shandar's PR but I don't know how to serialize it properly for the stacks-node to accept it. It can be serialized to JSON though.
> 
> https://docs.hiro.so/api#tag/Transactions/operation/get_raw_transaction_by_id
> 
> There's no request examples, only for responses.
> 
> I had a call with @sergey-shandar the other day and we talked about using yarpc to serialize the transaction properly. Here's how to call it manually https://github.com/Trust-Machines/core-eng/tree/main/yarpc/js/stacks
> 
> There are two questions for me now:
> 
> 1. How do I call this code programmatically from the stacks-coordinator?
> 2. What kind of transaction do we expect in the stacks-coordinator's `broadcastTransaction()` and which function do we need from here https://github.com/hirosystems/stacks.js/tree/master/packages/transactions ?

**Comment by stjepangolemac** [comment]
Nice work @donpdonp, thanks for cleaning up my PR 🙏

**Comment by sergey-shandar** [comment]
It looks like there is more pressure to create `stacks.rs` lib and throw away JS/Deno intro.
