### ISSUE TITLE
[stacks-coordinator] test integration with stacks-node

### ISSUE THREAD

**Issue by donpdonp** [Trust-Machines/core-eng#181]
Using current version of core-eng, run stacks-coord against the next-branch stacks-node. Make a ticket for what is broken or incomplete. The node will have no peg-requests but even processing an empty json list would be a success for stacks-coordinator.

**Comment by donpdonp** [comment]
using next-branch stacks-node
```
$ curl http://localhost:20443/v2/info | jq                   
{
  "peer_version": 4207599110,
  "pox_consensus": "fa6cc8658e6e50a18d78c6d62a2b8fbbd69e8d77",
  "burn_block_height": 2424889,
  "stable_pox_consensus": "f56726d48134f658ed206b219f511a0108d2c862",
  "stable_burn_block_height": 2424882,
  "server_version": "stacks-node 0.0.1 (next:dc1d931, release build, linux [x86_64])",
```
and the 5000 sat transaction in https://testnet.stx.eco/history the btc transaction is shown to be in testnet height 2423272

```
$ curl http://localhost:20443/v2/burn_ops/2423272/peg_in 
{"peg_in":[]}
```

shows no peg-in operations. should there be something here? (cc @kantai )

**Comment by jferrant** [comment]
I have a similar issue when attempting to access the peg_out_request. 

```bash
$ curl http://localhost:20443/v2/burn_ops/2423272/peg_out_request 
{"peg_out_request":[]}
```

**Comment by jferrant** [comment]
Also something i have noticed..it makes coding to handle error cases a bit more difficult in the case of non existent block heights. Rather than returning "Could not find burn block at height 1", would it be possible to have a nicer json response that indicates an error? Like `{"error": "Could not find burn block at height 1"}` @kantai

**Comment by kantai** [comment]
You'll have to consult the logs on the node to see what's going on. For burnchain operations, these log lines can help:

https://github.com/stacks-network/stacks-blockchain/blob/next/src/chainstate/burn/db/sortdb.rs#L4902-L4979

Note, those logs contain block height and operation type, so you can filter by operation type or by block height to see if burnchain operations were processed at the block height you queried at.

These log lines are also potentially helpful:

https://github.com/stacks-network/stacks-blockchain/blob/next/src/burnchains/burnchain.rs#L742-L946

You can also try to search for "peg in" or "peg out" in your logs.

**Comment by donpdonp** [comment]
Adding a comment from discord to have an example peg-in json as part of the ticket.
```
$ kubectl port-forward -n mining pod/stx-testnet-follower-next-blockchain-0 20445:20443
$ curl http://localhost:20445/v2/burn_ops/2425540/peg_in
{"peg_in":[{"recipient":"ST3N4AJFZZYC4BK99H53XP8KDGXFGQ2PRSPNET8TN","peg_wallet_address":"tb1pmmkznvm0pq5unp6geuwryu2f0m8xr6d229yzg2erx78nnk0ms48sk9s6q7","amount":55155,"memo":"0000000000000000000000000000","txid":"bf4241c1df78e9feaaae64cf0e9b5b6b42d50bf10a9eed2b56c6d4f9c22c0067","vtxindex":9,"block_height":2425540,"burn_header_hash":"000000000000001b68518824354edaa8eeb0e76c00e86ec25ba7ed6e8f948938"}]}
```

jq formatted
```
[
  {
    "recipient": "ST3N4AJFZZYC4BK99H53XP8KDGXFGQ2PRSPNET8TN",
    "peg_wallet_address": "tb1pmmkznvm0pq5unp6geuwryu2f0m8xr6d229yzg2erx78nnk0ms48sk9s6q7",
    "amount": 55155,
    "memo": "0000000000000000000000000000",
    "txid": "bf4241c1df78e9feaaae64cf0e9b5b6b42d50bf10a9eed2b56c6d4f9c22c0067",
    "vtxindex": 9,
    "block_height": 2425540,
    "burn_header_hash": "000000000000001b68518824354edaa8eeb0e76c00e86ec25ba7ed6e8f948938"
  }
]
```
