### ISSUE TITLE
Asana integration investigation

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/core-eng#191]
## Background
We're a distributed team, and our work is scattered across multiple repositories. Moreover, we have a high need for non-github related tasks such as this one. At the same time, other teams in our organization uses Asana to organize their work.

Historically, a blocker for us to use a tool like Asana has been the high importance of public transparency in our work. As a consequence, we have not been able to define a coherent team backlog of the priorities and focus of our team.

However, it has recently come to my knowledge that Asana supports a tight integration with github issues. We should explore if it is possible to migrate our current issue board to Asana, and improve our collaboration processes so that we

1. Have a single board we can put any task in the team.
2. Can maintain a backlog within the team of tasks and priorities.
3. Maintain public transparency and insight in what we do relating to open source projects.

## Definition of done

* The GitHub/Asana integration has been tested and evaluated.
* A decision on whether or not to migrate our work streams to Asana has been made by the entire team.

**Comment by igorsyl** [comment]
> Y'all are obviously free to choose whatever works for you within TM. I'd only caution that given the touchpoints with the broader stacks-blockchain development, if a TM-internal tool ends up impacting the workflow for non-TM blockchain engineers, you might want to keep that in consideration.

Thank you for your feedback @diwakergupta ! We are exploring a project management tool for internal use only. We aim to keep our development process as open as possible using GitHub tools.

**Comment by netrome** [comment]
Thank you for sharing your concerns @diwakergupta. We will only introduce internal tooling if it can enhance our collaboration within the team without impacting any external workflow. I will not accept any solution which would harm our public collaborations.
