### ISSUE TITLE
[stacks-coordinator] Broadcast transactions to the stacks node

### ISSUE THREAD

**Issue by jferrant** [Trust-Machines/core-eng#210]
The function itself is already implemented. However, all its calls are commented out. Renable them and test their functionality

**Comment by stjepangolemac** [comment]
So I was going to take over this one while @jferrant is away but it seems that every mention of the `broadcast_transaction()` function in the code is not commented. Also, it seems all the right places have it:

- peg in
- peg out request
- peg out fulfill

I suggest @netrome also takes a look so we can confirm that this is already done.

**Comment by netrome** [comment]
Yep, the function seems implemented to me. I guess testing is also part of this ticket, and the only test case calling this function has the comment "temporary debugging". So I guess we can either break out testing to a separate ticket, or implement testing within the context of this ticket
