### ISSUE TITLE
[frost-coordinator] Make a call to sBTC to retrieve the required config file options

### ISSUE THREAD

**Issue by jferrant** [Trust-Machines/core-eng#215]
The config file is currently used to get the following info:
total_signers
total_keys
keys_threshold
max_party_id

These should be retrieved from an sBTC contract call not a config file.

EDIT ALSO NEED:

signer_public_keys
key_public_keys
coordinator_public_key

**Comment by xoloki** [comment]
We also need to get pubkeys for the signers, both in the coordinator and in the signer.
