### ISSUE TITLE
[P-02] Sign and validate FROST shares

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/core-eng#229]
## Definition of done
Our FROST implementation only accepts signed messages.

```[tasklist]
### Milestones
- [ ] Define message format for signing
- [ ] Integrate signing in coordinator
```

**Comment by netrome** [comment]
Weekly opdate: The following is done:

frost-signer/-coordinator commands to generate private keys
These will be placed into the config for now
Every signer keeps their own private and everyone else’s public keys
Update all network messages to include a signature field
frost-signer/-coordinator signs all messages
frost-signer/-coordinator verifies all messages

This needs to be done:
stacks-signer/-coordinator gets public keys from sbtc contract and passes them down to frost-signer/-coordinator
frost-signer/-coordinator will store their private keys in an encrypted local store, password protected

**Comment by jferrant** [comment]
Is this done?

**Comment by xoloki** [comment]
> Is this done?

This is done

**Comment by xoloki** [comment]
Oh sorry we didn't do step 6 yet.  Do we still want that?  We would need to pass a command line arg or env var with the password to decrypt

**Comment by netrome** [comment]
> Oh sorry we didn't do step 6 yet. Do we still want that? We would need to pass a command line arg or env var with the password to decrypt

Yeah no let's skip it for alpha. I don't know how the signer is intended to run for subsequent releases but I guess this might be worth revisiting in the context of the signer workstream, but let's cross that bridge once we get there.
