### ISSUE TITLE
[stacks-signer] Design doc for stacks-signer

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/core-eng#24]
The stacks-signer process uses frost-signer and loads configuration from the `sbtc-alpha` contract.

Rough requirements:
https://docs.google.com/document/d/1KXBW6EpZZGCdBMUd2ILuPbJ8D5zE-yI3a8vdtH9sYLA/edit#

Please ensure everyone in the team reviews this document PR

**Comment by sergey-shandar** [comment]
Please, add very simple examples how to use stacks-signer API.
