### ISSUE TITLE
Add segwit to Bitcoin Clarity Library

### ISSUE THREAD

**Issue by FriendsFerdinand** [Trust-Machines/core-eng#253]
Add segwit to Bitcoin Clarity Library to respond to issue #152 

The Bitcoin Clarity Library is to be a sub-directory in the sbtc-mini directory.

**Comment by friedger** [comment]
This can happen in a separate contract.

**Comment by MarvinJanssen** [comment]
Possible API: https://github.com/Trust-Machines/core-eng/pull/269#discussion_r1167207793

**Comment by FriendsFerdinand** [comment]
My WIP is here: https://github.com/FriendsFerdinand/clarity-bitcoin/tree/feat/segwit
Parsing segwit txs is done.

**Comment by jo-tm** [comment]
working repo is Trust-Machines/clarity-bitcoin

**Comment by jo-tm** [comment]
@FriendsFerdinand will merge from his repor the clarity-bitcoin

**Comment by FriendsFerdinand** [comment]
Wrote a first version. Creating a PR when I get permission. Need to test further.

**Comment by jo-tm** [comment]
@igorsyl he has permissions now, marten added some permission to create PRs in core-eng.

**Comment by jo-tm** [comment]
Fernando will add test contract for headers.

**Comment by jo-tm** [comment]
@FriendsFerdinand  can you please provide an update on this and the tests here?

**Comment by jo-tm** [comment]
Fernando adding 1 more test on this. Blocked by Peg-In Vector Tests. cc/ @netrome

**Comment by netrome** [comment]
> Fernando adding 1 more test on this. Blocked by Peg-In Vector Tests. cc/ @netrome

FYI @soju-drinker

**Comment by FriendsFerdinand** [comment]
Ok, we can start adding tests with this: https://github.com/Trust-Machines/core-eng/pull/334/files

**Comment by jo-tm** [comment]
More test vector will be added by Fernando.

**Comment by jo-tm** [comment]
- Fernando need reviews, from Friedger or another Engs.
- Can merge this week.

**Comment by jo-tm** [comment]
- Needs more reviews.
- @MarvinJanssen can add a review.
- Can merge after review.

**Comment by jo-tm** [comment]
- Marvin proposed some changes.

**Comment by jo-tm** [comment]
- post any updates if applicable here.
- @FriendsFerdinand  please plan for Date Completion to be 16th June or June or 30th June (or earlier), use the **Week** field. So we have 2-week Sprint Granularity for June and not 1 week that is too tight. Also, add an **Estimation of #Days** for @igorsyl Gantt if you want.

**Comment by FriendsFerdinand** [comment]
@jo-tm it's done
