### ISSUE TITLE
Asset Contract

### ISSUE THREAD

**Issue by jo-tm** [Trust-Machines/core-eng#279]
## Background
A special SIP10 implementation, designed specifically to keep a pegged 1:1 parity with Bitcoin. In addition to standard SIP10 functions, the focus of this contract is to mint, burn, lock, and unlock sBTC tokens as mandated by the sBTC protocol.

## Key Non-SIP10 Features

1. Mint sBTC (for a successful peg-in)
2. Burn sBTC (for a successful peg-out)
3. Lock sBTC (for a peg-out request)
4. Unlock sBTC (for reclaiming tokens on peg-out request expiry)
5. Guarding these features to only allow protocol contracts to successfully invoke them.

## Definition
The sBTC token contract implements the SIP010 trait for fungible tokens so that they may be traded freely. It includes a mechanism that allows for minting and burning of tokens at-will by sBTC Mini protocol contracts.

## Motivation
The sBTC asset is fundamental to the sBTC protocol. Without it, the sBTC protocol cannot exist as Bitcoin cannot be swapped into a 1:1 parity asset.

## Technical Risk
Risks are low since SIP010 fungible tokens are well understood. As the asset contract contains no logic specific to the sBTC protocol itself (outside of asserting that the caller is part of the protocol), it should be straightforward to implement the contract.

## Dependencies
P-XX sBTC Mini Controller Contract

## Rough implementation plan & timeline

Completion is measured in five sub-deliverables:

- The contract implements SIP010.
- The contract can query the controller to see if the contract caller is part of the protocol.
- The contract implements mint and burn, guarded by (2).
- The contract implements lock and unlock, guarded by (2).
- The contract allows for metadata updates, guarded by (2).

The workload estimate for this project is 1-2 workdays.

**Comment by MarvinJanssen** [comment]
Pretty much already implemented in #269.

**Comment by jo-tm** [comment]
@MarvinJanssen : almost finished but no unit test yet, usual token contract.

**Comment by friedger** [comment]
I'd love to see a streamlined way for these standard tasks

**Comment by MarvinJanssen** [comment]
Comprehensive unit tests in #290

**Comment by jo-tm** [comment]
part of Clarity WG.

**Comment by jo-tm** [comment]
experimental testing in Clarity by @MarvinJanssen : https://github.com/Trust-Machines/core-eng/pull/290

**Comment by jo-tm** [comment]
We have to conform with SIPs.

**Comment by jo-tm** [comment]
Closed by https://github.com/Trust-Machines/core-eng/pull/269

**Comment by jo-tm** [comment]
- Also includes CI in the Unit Testing branch.
- Compare with WIP SIPs.
