### ISSUE TITLE
[stacks-coordinator] Create cli application

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/core-eng#29]

**Comment by netrome** [comment]
The frost-coordinator already has a CLI. What's the definition of done for this issue?

**Comment by igorsyl** [comment]
Let's prioritize stacks-coordinator cli application. Marking this as backlog.

**Comment by xoloki** [comment]
Hey @igorsyl, is this still valid for frost-communicator?  We have dkg/sign/dkgsign available now for frost-communicator, which all work.

**Comment by igorsyl** [comment]
> Hey @igorsyl, is this still valid for frost-communicator? We have dkg/sign/dkgsign available now for frost-communicator, which all work.

The signer user should be able to run something like this to manually trigger a new DKG run
```
$ sbtc-signer dkg run
```
In a separate process, they would have something like this looping to handle sign requests
```
$ sbtc-signer loop
```
