### ISSUE TITLE
[stacks-coordinator] write tests to spin up bitcoind and test all bitcoin node calls

### ISSUE THREAD

**Issue by jferrant** [Trust-Machines/core-eng#295]
Might want to take a look at frost-btc test and pull out functionality into a util to be used in some stacks tests as well.

See: 
https://github.com/Trust-Machines/core-eng/blob/main/frost-test/src/bitcoind.rs
https://github.com/Trust-Machines/core-eng/blob/main/frost-test/tests/frost-btc.rs#L115

One option is to rename frost-test to be more generic so it can include frost and stacks involved testing.

**Comment by stjepangolemac** [comment]
@jferrant would it make sense if we extracted the common utils into a separate lib and then have frost-test and stacks-coordinator-test that use it?

**Comment by jferrant** [comment]
> @jferrant would it make sense if we extracted the common utils into a separate lib and then have `frost-test` and `stacks-coordinator-test` that use it?

This is actually was my preference a while ago but I was advised against. However, I think it is still the best approach given how large the bitcoind component is/considering I will have to write a similar component that spins up a stacks-node. 

Maybe we go with `common-utils` (this may help with determining the stacks.rs functions we want too) and `stacks-test` and `frost-test` can then just utilize it.

**Comment by stjepangolemac** [comment]
Okay I'll make something like that and we can steer it when we have some something to review.
