### ISSUE TITLE
[stacks-signer] Add signer cli tool to create signer private key

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/core-eng#31]
@donpdonp to add details

**Comment by xoloki** [comment]
Hey @igorsyl , can you give some specifics what you're looking for in this issue?  Do you want the stacks signer to make a private key for frost protocol message signing?  Or are you saying to run DKG and get a share of the group key?

**Comment by xoloki** [comment]
I'm also assuming it's for the first.  We will need an ecdsa key for frost protocol message signing.

However, I haven't actually exposed those bits from libsecp256k1 in the p256k1 crate.  But the private key is just a Scalar, which encodes to 32 bytes.  So if you just add a cli to make a random Scalar and print out the base 58 string rep that should suffice.
