### ISSUE TITLE
Don't require zero-padded data for commit-reveal

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/core-eng#341]
Commit reveal currently requires the data to be 86 bytes, 78 coming from the OP_RETURN format. However, OP_RETURN data may be shorter than 78 bytes (plus two magic bytes). We should explicitly allow commit reveal data to be shorter than 86 bytes.

## Definition of done
The commit-reveal spec has been updated to allow for shorter byte lengths.

**Comment by radicleart** [comment]
@netrome just checking.. the Clarity does have access to the length of the <data> from the witness data of the Bitcoin transaction ? If it does it should be able to infer the length of the stacks data and read the variable length contract name if it is present. If not then we probably need the fixed length format. Maybe @MarvinJanssen can confirm ?

**Comment by MarvinJanssen** [comment]
What was the background for requiring data to be zero-padded? Just so we know where each data field start, or is there more to it?

In any case, it looks like there are at least two types of variable length data; namely, optional contract name and memo. Length-prefixing makes it much easier to jump over portions in Clarity to extract the information we need. Otherwise we have to interpret the entire buffer and read each byte with a map or a loop, which will add significant runtime costs.

@radicleart can you elaborate on your question? The entire witness is posted to the Clarity contract along with the Bitcoin transaction, otherwise we cannot verify (pending #275) the output was consumed correctly. We extract the data payload from the witness to make the sBTC mint/burn happen.

**Comment by radicleart** [comment]
> can you elaborate on your question?

I noticed the first byte of the witness section which contains the stacks payload indicates the length of the payload. I thought that would be enough to avoid padding and for the clarity to be able to easily parse the data. However, I wasn't aware of the memo field at that point. Taking this into account I can see that prefixing the optional contract name and optional memo with a byte to indicate the length of each is necessary if we want to remove the need for the zero padding.

As to why the padding is necessary in the first place I'm not sure.

There's a bit more context for this came on [discord](https://discord.com/channels/1076608263983997008/1105549945588690964/1106512014211293244).

**Comment by netrome** [comment]
Padding was never necessary. The original spec was just cautious to not allow variable length payloads, assuming an OP_RETURN would use up it's allocated 80 bytes, and also making it easy to know exactly where the reveal fee are for parsing. However, afaik there's no good reason not to allow for variable length payloads hence why we're updating this :)

**Comment by radicleart** [comment]
> data may optionally contain a memo affecting

Wondering where the optional `memo` field enters - I searched the SIP-021 and Master sBTC doc and can't find a mention of it ?

**Comment by netrome** [comment]
> > data may optionally contain a memo affecting
> 
> Wondering where the optional `memo` field enters - I searched the SIP-021 and Master sBTC doc and can't find a mention of it ?

Yeah, it's not in the SIP since it's not part of the protocol. See it more as a Stacks-specific implementation detail. Here's Jude's comment on my first wire-format PR where he mentions it: https://github.com/stacks-network/stacks-blockchain/pull/3486

**Comment by radicleart** [comment]
Ok thanks for the info. I'll update the commit tx in the bridge based on the following - and update once this is finalised your side;

```
0  1                            n
|--|----------------------------|
 op             data
```
where data is now..

```
data = {
   network version: 1 byte,
   c32 encoded stacks address: 20 bytes,
   length of contract name: 1 byte ( equals 0 if no contract name),
   contract name: n bytes (see previous),
   length of memo: 1 byte (equals 0 if no memo),
   memo: m bytes (see previous field)
   reveal fee: 8 bytes (big endian number of satoshi)
}
```

**Comment by netrome** [comment]
> Ok thanks for the info. I'll update the commit tx in the bridge based on the following - and update once this is finalised your side;
> 
> ```
> 0  1                            n
> |--|----------------------------|
>  op             data
> ```
> 
> where data is now..
> 
> ```
> data = {
>    network version: 1 byte,
>    c32 encoded stacks address: 20 bytes,
>    length of contract name: 1 byte ( equals 0 if no contract name),
>    contract name: n bytes (see previous),
>    length of memo: 1 byte (equals 0 if no memo),
>    memo: m bytes (see previous field)
>    reveal fee: 8 bytes (big endian number of satoshi)
> }
> ```

Perfect. Head's up @radicleart, we're discussing including another byte before the stacks address to make the format compatible with the wire format for stacks principals. (Marvin's original comment on this: https://github.com/Trust-Machines/core-eng/pull/339#discussion_r1194208407)  Let me know if you have any opinions on this.

**Comment by netrome** [comment]
@radicleart @MarvinJanssen PR opened https://github.com/Trust-Machines/core-eng/pull/348

**Comment by radicleart** [comment]
> discussing including another byte

Brilliant thanks for the heads up. Whatever makes life easier, faster, more readable in the Clarity is absolutely the driver from my point of view.
