### ISSUE TITLE
[Process] Improved visibility of dependencies

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/core-eng#39]
Currently we only encode dependencies between issues in their description, which is not optimal for anyone who want's to get a birds-eye view of the project.

DoD: We have a good way of visualizing dependencies between issues.

**Comment by igorsyl** [comment]
We can use this:

https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists
https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists

**Comment by netrome** [comment]
> We can use this:
> 
> https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists

Cool. Will that be visible in the [project overview page](https://github.com/orgs/Trust-Machines/projects/5/views/4)?

**Comment by igorsyl** [comment]
> > We can use this:
> > https://docs.github.com/en/issues/tracking-your-work-with-issues/about-tasklists https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists
> 
> Cool. Will that be visible in the [project overview page](https://github.com/orgs/Trust-Machines/projects/5/views/4)?

Yes, there are new columns "Tracks" and "Tracked by" which show parent and children deps.

**Comment by netrome** [comment]
> > Cool. Will that be visible in the [project overview page](https://github.com/orgs/Trust-Machines/projects/5/views/4)?
> 
> Yes, there are new columns "Tracks" and "Tracked by" which show parent and children deps. @netrome

Nice. Hmm... I updated #12 but I did not see anything pop up in those columns :thinking:
