### ISSUE TITLE
Multiple reveals per Bitcoin transaction

### ISSUE THREAD

**Issue by MarvinJanssen** [Trust-Machines/core-eng#409]
Right now, in #319 I implemented submitting a peg in reveal proof in order to mint sBTC. (The proof being the Bitcoin transaction that spent the escrow P2TR output.) However, it is made such that the signers can spend only one escrow escrow P2TR output per Bitcoin transaction.

See here:
https://github.com/Trust-Machines/core-eng/blob/37a99ba40e2f55310b7e9aa1ad5da1b39bf3381c/sbtc-mini/contracts/sbtc-peg-in-processor.clar#L76-L89

But we could also allow multiple reveals per transaction (up to 8 inputs per Bitcoin transaction). Is it something we want to allow?

I do not yet know whether it is feasible from a runtime cost perspective, but should be fine once we have an optimised clarity-bitcoin library for sBTC.

cc @netrome @jo-tm @FriendsFerdinand

**Comment by netrome** [comment]
Oh I like this idea! This would require us to figure out some things like how to organize the outputs of the reveal transactions when they are a part of the protocol, and it would also require some more tweaks to the stacks-node code (which I don't know if it's feasible or not).

I'll create an issue for the blockchain working group to look into this.

**Comment by netrome** [comment]
I created https://github.com/Trust-Machines/core-eng/issues/409 to investigate the feasibility from the blockchain perspective.

I'd also be interested to know the priority of supporting this from a UX/GTM perspective. We'll save fees by aggregating the reveals, but as any scope increase it will take more time. @igorsyl or @andrerserrano do you have any input here? Is it worth to spend some time to investigate the possibility of aggregating multiple reveal transactions or is our timeline so tight that we won't do it for the initial sBTC launch anyway?

Initial guesstimations from me: Investigating if this is doable and updating the implementation plan, 4hrs of work. Actual extra work to implement this (high uncertainty): +1 week.

**Comment by MarvinJanssen** [comment]
For completeness: it is not a lot of added work on the Clarity side I think. On the node I of course cannot comment.

**Comment by MarvinJanssen** [comment]
Closing this for now to follow along with #413. Feel free to re-open once that issue is re-opened.
