### ISSUE TITLE
[stacks-coordinator] Sign peg-out fulfillments

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/core-eng#52]
Once we have a functional frost-coordinator integrated and a FeeWallet capable of producing peg-out-fulfillment transactions, we need to combine these two to unlock the peg-out fulfillment input UTXO(s) from the fee wallet.

## Dependencies
- #15 

## Definition of done
We have a provided function (or equivalent functionality) on the FrostCoordinator trait, capable of unlocking the inputs of a transaction.
```
fn unlock_inputs(&self, tx: BitcoinTransaction) -> BitcoinTransaction
```

Any appropriate unit tests are written & updated.

**Comment by igorsyl** [comment]
re FeeWallet: are splitting into BitcoinWallet and StacksWallet?

**Comment by netrome** [comment]
Let's leave that for the implementors of #14 and #15 to decide.

**Comment by donpdonp** [comment]
src/coordinator.rs line 72 currently says `sign_message(&fulfill_tx.serialize())?;`
tx.serialize() is the wire-format for the entire transactions, that isnt what gets signed. 

What needs to be signed is the 'sighash', which is built in the lines below:
https://github.com/Trust-Machines/core-eng/blob/test-frost-btc-libonly/frost-test/tests/frost-btc.rs#L69

Once the signature is in hand, there should be another function to do the following:

The signature bytes need to be put into tx.inputs[0].witness 
https://docs.rs/bitcoin/latest/bitcoin/blockdata/witness/struct.Witness.html#method.push

(fyi inputs is an array of)
https://docs.rs/bitcoin/latest/bitcoin/blockdata/transaction/struct.TxIn.html

Make a p2tr script to go in the input[0].script
https://docs.rs/bitcoin/latest/bitcoin/blockdata/script/struct.Script.html#method.new_v1_p2tr

Also this SE post has some relevant information on taproot transactions
https://bitcoin.stackexchange.com/questions/116589/signing-taproot-key-path-transaction-from-rust-bitcoin
