### ISSUE TITLE
stacks-dev-guide: add link to instructions on how to run a radon node

### ISSUE THREAD

**Issue by igorsyl** [Trust-Machines/core-eng#59]
https://twitter.com/judecnelson/status/1623151711530504192

https://gist.github.com/jcnelson/c5f43cbefba3727dcccf5a95209b60fc

**Comment by igorsyl** [comment]
@jferrant to review

**Comment by empeje** [comment]
I'll close this ticket as it is implemented in #143 

cc: @igorsyl
