### ISSUE TITLE
Review PegQueue

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/core-eng#68]
PR: https://github.com/Trust-Machines/core-eng/pull/62

**Comment by igorsyl** [comment]
It seems like this is ineffective because GitHub Project doesn't send notifications.

**Comment by netrome** [comment]
Well, worth a shot at least. Let's help remind each other to monitor https://github.com/pulls/review-requested daily. I think we'll be able to converge to a healthy review routine with that.
