### ISSUE TITLE
Peg-handoff design & implementation plan

### ISSUE THREAD

**Issue by netrome** [Trust-Machines/core-eng#80]
We need to figure out which pieces that must be in place to deliver the peg hand-off functionality.

According to the sBTC technical [roadmap draft](https://docs.google.com/spreadsheets/d/1DwLNts95_4olTXKFI1sV7kF47UlvbpmdADfhUtZ9xJA) we should have a peg-handoff system delivered by May 10. This should include the peg hand-off wire formats, as well as the ability for stackers to construct this transaction - perhaps initiated by the coordinator?

## Definition of done
- The requirements for the peg hand-off system are well defined and we have an initial implementation plan for this.

**Comment by netrome** [comment]
The design and implementation plan is part of the overall [sBTC scoping document](https://docs.google.com/document/d/10s9Wh_GrRxcRg9MfsKeKv2Z2y6Ebi9vPIgBOVWI7-VM/) now.

**Comment by netrome** [comment]
My aim is to define follow-up tasks to initiate the implementation of this by next week.

**Comment by igorsyl** [comment]
I imagine we'd want the first round of tasks ready by EOW.
