### ISSUE TITLE
Rust-analyzer crashes / hangs when working on the stacks-blockchain repo

### ISSUE THREAD

**Issue by stjepangolemac** [Trust-Machines/core-eng#86]
Logs from my editor (Zed):

![image](https://user-images.githubusercontent.com/15632814/220900311-e473b39d-d9e5-4fea-b8ba-2ce58cd98399.png)

> To give you a bit more context, here's the project that always breaks down Zed's LSP.
> 
> https://github.com/stacks-network/stacks-blockchain/tree/master/testnet/stacks-node
> 
> If you open the file below, and make a change anywhere, the LSP stops working.
> 
> https://github.com/stacks-network/stacks-blockchain/blob/master/testnet/stacks-node/src/tests/neon_integrations.rs
> 
> I can do a "editor: restart language server" and it will work until the next change.
> 
> Let me know if I can help you in any way. Unfortunately, this forces me to move to a different editor until it's resolved.
> 
> NOTE: VSCode with the rust-analyzer plugin works without issues.

As written here https://github.com/zed-industries/community/issues/971

For context, I'm using the Zed editor but this is happening for @netrome with helix also. For some reason works with VSCode and CLion.

**Comment by stjepangolemac** [comment]
I'm now trying to run RA manually and see if I can spot some clear error logs.

**Comment by igorsyl** [comment]
Did removing the benches help at all?

**Comment by stjepangolemac** [comment]
Just tried that and it behaves in the same way. I'm inclined to think these editors are just not properly talking with the LSP.

**Comment by igorsyl** [comment]
Flag it to the zed devs. Unfortunately, too much work to reverse-engineer closed-source software.
Have you tried CLion? You can get it to work with keyboard shortcuts for a no-mouse experience.

**Comment by stjepangolemac** [comment]
It's not only Zed but Helix too, both say that the LSP requests time out. Maybe they need to increase the threshold or something.

I've checked out CLion and the new UI from Jetbrains but I'm back to VSCode again.

**Comment by igorsyl** [comment]
Let me know if VSCode is too much of a compromise from Zed/Helix in a couple of weeks.

**Comment by stjepangolemac** [comment]
This still happens but is much more rare now. Will close, I think it's an editor bug.
